name: app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  data:
    path: ../data
  domain:
    path: ../domain
  shared:
    path: ../shared
  get_it: ^7.6.7
  injectable: ^2.3.2
  freezed_annotation: ^2.4.1
  flutter_bloc: ^8.1.4
  auto_route: ^7.8.4
  flex_color_scheme: ^7.3.1
  responsive_builder: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  injectable_generator: ^2.4.1
  freezed: ^2.4.7
  auto_route_generator: ^7.3.2

flutter:
  uses-material-design: true
