name: shared
description: "A new Flutter package project."
version: 0.0.1
publish_to: 'none'
homepage:

environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  bloc_clean_arch:
    git:
      url: https://github.com/cvphat/bloc_clean_arch.git
      ref: v0.0.8
  intl: ^0.19.0
  get_it: ^7.6.7
  injectable: ^2.3.2
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  intl_utils: ^2.8.7
  build_runner: ^2.4.8
  injectable_generator: ^2.4.1
  freezed: ^2.4.7
  
flutter:

flutter_intl:
  enabled: true
  main_locale: en
  output_dir: lib/src/generated
  arb_dir: lib/src/l10n